### ISSUE TITLE
bz.w

### ISSUE THREAD

**Issue by 66oway** [corestudi0/corestudi0.github.io#13]
在线扒站工具 https://bazhan.wang

**Comment by corestudi0** [comment]
其实没必要，可以直接fork或者打包下载这个仓库

**Comment by 66oway** [comment]
> 其实没必要，可以直接fork或者打包下载这个仓库

那你这个网页不也是用这个在线扒站工具扒的，还自己加广告，真无耻

**Comment by xiaoqinnan3** [comment]
> 其实没必要，可以直接fork或者打包下载这个仓库

fork完之后怎么用？怎么变成网页？
