### ISSUE TITLE
网站代码是否公开可用？

### ISSUE THREAD

**Issue by Hakuin123** [corestudi0/corestudi0.github.io#3]
网站代码是否公开可用？

如果开源请附带上开源协议

想搬运一份/newyear，但是无开源协议的项目，GitHub默认原作者保留所有权利，故在此请求

另祝新年快乐！

**Comment by Hakuin123** [comment]
想获取的是此修改过的版本

**Comment by qiangmouren** [comment]
/newyear 的源码来自 http://20it.cn/a1023461

corestudi0 在把公众号链接去掉后才发布出来

**Comment by corestudi0** [comment]
开源的但是不知道怎么设置协议就很尴尬qwq

**Comment by qiangmouren** [comment]
> 开源的但是不知道怎么设置协议就很尴尬qwq

还想着加广告呢

**Comment by mlmk01** [comment]
要什么协议开源就有本身的协议

**Comment by mlmk01** [comment]
快快把源码发出来，我想要你修改后的，求求了

**Comment by xiaoqinnan3** [comment]
这个有了源码怎么用？变成网页的

**Comment by mlmk01** [comment]
> 这个有了源码怎么用？变成网页的

Gitee，github都有页面的，可以直接生成链接

**Comment by xiaoqinnan3** [comment]
> > 这个有了源码怎么用？变成网页的
> 
> Gitee，github都有页面的，可以直接生成链接

具体操作怎么搞得？不理解

**Comment by qiangmouren** [comment]
在线扒站工具 https://bazhan.wang/
