### ISSUE TITLE
感谢祝福

### ISSUE THREAD

**Issue by HJH645** [corestudi0/corestudi0.github.io#7]
好棒的代码！想把文案修改一下哈哈哈  好老的套路

**Comment by qiangmouren** [comment]
/newyear 的源码来自 http://20it.cn/a1023461

这个仓库他把人家的公众号链接去掉后发布了出来

**Comment by corestudi0** [comment]
> /newyear 的源码来自 http://20it.cn/a1023461
> 
> 这个仓库他把人家的公众号链接去掉后发布了出来

我之前忘记说了，我是和20it.cn他们工作室合作的(因为流量多)，不信的话我可以发截图
