### ISSUE TITLE
能不能用一下你的代码？

### ISSUE THREAD

**Issue by xiaoqinnan3** [corestudi0/corestudi0.github.io#9]
怎么下载下来？

**Comment by corestudi0** [comment]
可以，直接fork就可以

**Comment by xiaoqinnan3** [comment]
> 可以，直接fork就可以

怎么搞？在哪里

**Comment by corestudi0** [comment]
在code页面应该可以找到fork按钮，如果不行在code页面点击code然后下载压缩包即可

**Comment by qiangmouren** [comment]
https://bazhan.wang/

**Comment by xiaoqinnan3** [comment]
> 在code页面应该可以找到fork按钮，如果不行在code页面点击code然后下载压缩包即可

我是手机端，好像没有
